### ISSUE TITLE
Image conversion reproducibility

### ISSUE THREAD

**Issue by 53RT** [fjeg/ddsm_tools#1]
Dear fjeg,

I am trying to convert the DDSM normal scans with the same procedure as the scans from the CBIS-DDSM were converted.
I noticed in the code provided, the od value is clipped to the range [0.05-3] but then remapped from [0-4] to [0 - 255] which doesn't fit in terms of the intensity and the bit depth from the CBIS-DDSM set. 

Can you tell me what the original procedure for creating the CBIS-DDSM set was?

Thanks alot

**Comment by fjeg** [comment]
We clipped values outside of 0.05-3 as per noise correction from original DDSM code. You can see commentary here under the file "make_reduced_images":
http://marathon.csee.usf.edu/Mammography/software/heathusf_v1.1.0.html

We mapped [0,4] to the range [0,255] because the limits of optical density are unchanged. The clipping was only for noise reduction at limits of optical density spectrum.

**Comment by 53RT** [comment]
Thanks for your reply. I think I've found the problem.

If I want my converted images exactly match the cbis-ddsm I need to map od to 16 bit from the clipped values.
I checked for one corresponding scan and also np.allclose is true.

![histograms](https://user-images.githubusercontent.com/11428204/47426534-c4fbd880-d78d-11e8-8d8b-bdf294e2a897.png)

But one question still remains what did you need the 8 bit quantized images for?

**Comment by fjeg** [comment]
Glad it worked out. My colleague likely went to 16bit when publishing the data set since it would be less lossy.

As for my reasons for 8 bit: we found that lower precision numbers have better performance in deep learning models. Many of our colleagues have had similar results. So they both cut memory reuquiremebts in half, and get better test set performance. There is some hand wavy argument saying it’s implicit regularization, but no concrete proofs.

**Comment by Betty-J** [comment]
> hi, I am recently tring to convert this datasets, and the converted image differs from CBIS_DDSM, Could you please share the detailed image conversion process to make the generated dicom image consistent with CBIS_DDSM?! 

Thanks a lot and best wishes.

**Comment by pedrohbd** [comment]
> Dear fjeg,
> 
> I am trying to convert the DDSM normal scans with the same procedure as the scans from the CBIS-DDSM were converted. I noticed in the code provided, the od value is clipped to the range [0.05-3] but then remapped from [0-4] to [0 - 255] which doesn't fit in terms of the intensity and the bit depth from the CBIS-DDSM set.
> 
> Can you tell me what the original procedure for creating the CBIS-DDSM set was?
> 
> Thanks alot

Dear 53RT, can you share the converted DDSM normal scans somehow? It would be great if they were available in the CBIS-DDSM too as they also have value for training DL models. Thanks!

**Comment by pedrohbd** [comment]
> Dear fjeg,
> 
> I am trying to convert the DDSM normal scans with the same procedure as the scans from the CBIS-DDSM were converted. I noticed in the code provided, the od value is clipped to the range [0.05-3] but then remapped from [0-4] to [0 - 255] which doesn't fit in terms of the intensity and the bit depth from the CBIS-DDSM set.
> 
> Can you tell me what the original procedure for creating the CBIS-DDSM set was?
> 
> Thanks alot

Dear 53RT, can you share the converted DDSM normal scans somehow? Actually, it would be great if they were available in the CBIS-DDSM too as they also have value for training DL models
